spring:
  profiles:
    active:
    - dev

 ---
 spring:
   profiles: dev
   application:
     name: lucifer-config-dev
 

 ---
 spring:
   profiles: test
   application:
     name: lucifer-config-test